name: Mosaika
favicon: null
layout_spectrum: 0.590797430370003
typography_spectrum: 0.17050443356856704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.30835580290295184
  lightness: 0.590374490711838
  saturation: 0.3215794281568378
  rhythmicContrast: 0.23142191115766764
purpose: []
