name: Mosaika
favicon: null
layout_spectrum: 0.37342
typography_spectrum: 0.6696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b342e'
    - '#b4a797'
    - '#ede8e4'
    - '#746b62'
    - '#060b0f'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
